DM-48092: Fix bug with peak detection in images with negative bbox origins
lsst/afw pull request #758
Opened 2024-12-19 00:37 UTC by taranu

2025-01-07 23:30 UTC, parejkoj requested changes
Should the function definition instead be changed to take `long const margin = 0` instead of `size_t`? The only call to `findPeaksInFootprint` in the stack that I can find passes `margin=1` in this same file, so there's no API compatibility problem to worry about. This is my main question, and would greatly simplify the fix (especially since you already have a test that triggers it).

2025-01-07 23:54 UTC, parejkoj commented
> Hmm, I thought about it but didn't want to change an old API like this. Having said that, I can't imagine anyone actually needing a margin larger than `unsigned int` (until someone invents uhhh exapixel CCDs), let alone long long, so if you're fine with it I'll change it to unsigned long.

Heh, I already changed this API without warning 3 years ago!

https://github.com/lsst/afw/commit/11de8edc6ac75a756342c921f666657841d943b0

`findPeaskInFootprints` is local to this file (local anonymous namespace), so nothing else could possibly call it anyway.

2025-01-07 23:55 UTC, parejkoj commented
`so if you're fine with it I'll change it to unsigned long` - wait, isn't the problem that it should be signed, not unsigned?

2025-01-08 00:01 UTC, taranu commented
> `so if you're fine with it I'll change it to unsigned long` - wait, isn't the problem that it should be signed, not unsigned?

Oh yes, it needs to be a signed value internally, but the input should either be unsigned or otherwise there ought to be a check that it's not negative - I suspect negative values could lead to out-of-range errors.

2025-01-08 00:14 UTC, timj commented
My opinion is that unsigned ints can be very annoying and prone to bugs and given that we aren't at the limit of a signed int it might be easier all around to use signed ints and a check to make sure it's not negative.

2025-01-08 00:55 UTC, parejkoj commented
Again, though, this file-local function is only called once, in the same file, with `margin=1`, so I think we're overthinking it.

2025-01-08 18:58 UTC, taranu commented on src/detection/FootprintSet.cc
> +    const auto image_y0 = image.getY0();
Ah, I missed some replacements. The compiler probably inlines, yes, but I don't see any harm in doing it explicitly.

2025-01-08 18:59 UTC, taranu commented on tests/test_footprint2.py
> +        img_peaks.set(0)
I copy-pasted the initial code from other tests so many of them will have similar oversights (or old patterns).

2025-01-08 19:01 UTC, taranu commented on tests/test_footprint2.py
> +        img_peaks.array[1, 1:4] = [10, 5, 10]
The actual peak values don't matter; in the existing code, as long as one of the origin values (x or y) is negative then all comparisons will fail and no peaks will be added (because either x_min or y_min can underflow to the max value with a small enough margin). It's just that the y value is checked first.

2025-01-08 19:03 UTC, taranu commented on tests/test_footprint2.py
> +        ds = afwDetect.FootprintSet(img_peaks, afwDetect.Threshold(5))
It's copypasta and occurs 8 times in this file. I don't know what ds signifies either.

2025-01-08 19:04 UTC, parejkoj commented on src/detection/FootprintSet.cc
> +    const auto image_y0 = image.getY0();
The harm is that it adds clutter and is unnecessary.

2025-01-08 19:19 UTC, taranu commented on src/detection/FootprintSet.cc
> +    const auto image_y0 = image.getY0();
How can you be certain it's unnecessary? `getX0` and `getY0` aren't even inline functions, and inline is a recommendation rather than a guarantee anyway.

By that argument the existing `bbox = image.getBBox();` line above should be removed too.

2025-01-08 19:21 UTC, parejkoj commented on src/detection/FootprintSet.cc
> +    const auto image_y0 = image.getY0();
I agree that that existing line should be removed. I'm in the "trust the compiler to do the right thing" camp.

2025-01-08 20:37 UTC, parejkoj approved these changes

2025-01-08 22:19 UTC, merged

2025-01-08 22:26 UTC, taranu commented on src/detection/FootprintSet.cc
> +    const auto image_y0 = image.getY0();
In case anyone was following this, @parejkoj did some simplified tests on godbolt and found (tl;dr) more aggressive inlining than I was expecting - but also calls were completely optimized out with too-trivial examples.

At any rate, I'm still in the opposite camp where I don't think explicitness harms readability even if it's potentially redundant. But more importantly, we both learned that [bear can be used with scons](https://developer.lsst.io/cpp/compilation-db.html) to test this with the aid of IDEs if necessary; I might try that in the future. I'm not sure how trivial that will be because while CLion can import a single `compile_commands.json` as a project, I don't think it can easily handle our library/package structure with multiple compilation databases.